from pathlib import Path

path = Path('backend/app/services/client_intent_runtime.py')
text = path.read_text()
old = '''    # Standalone Independent Living is not licensed as an RFG in Nevada. Missing\n    # HCQC RFG grades are NOT_APPLICABLE, not lower-quality evidence. Known\n    # adverse regulatory history still penalizes licensed/hybrid products.\n    pure_independent = (\n        _upper(row.get("canonical_type")) == "INDEPENDENT_LIVING"\n        and "ASSISTED_LIVING" not in modalities\n        and "ASSISTED_LIVING_RFG" not in modalities\n        and "SKILLED_NURSING" not in modalities\n    )\n    if pure_independent:\n        disciplinary_order = 0\n        grade_order = 0\n        counts = {}\n    else:\n        disciplinary = _upper(history.get("disciplinary_action"))\n        disciplinary_order = 0 if disciplinary == "N" else (2 if disciplinary == "Y" else 1)\n        counts = history.get("grade_counts") if isinstance(history.get("grade_counts"), dict) else {}\n        latest_grade = _upper(history.get("latest_known_grade"))\n        grade_order = {"A": 0, "B": 1, "C": 2, "D": 3, "UNKNOWN": 4}.get(latest_grade, 4)\n'''
new = '''    # Nevada does not license standalone Independent Living as an RFG. When an\n    # Independent Living product is the care-setting fit being compared, an RFG A/B\n    # grade on a hybrid campus is not positive evidence about its IL product and must\n    # not outrank a standalone IL community merely because the latter has no RFG grade.\n    # Adverse regulatory evidence (disciplinary action or C/D) remains a penalty.\n    independent_capable = care_status in {"PRIMARY_FIT", "POSSIBLE_FIT"} and (\n        "INDEPENDENT_LIVING" in modalities or "LIFE_PLAN_CCRC" in modalities\n    )\n    disciplinary = _upper(history.get("disciplinary_action"))\n    latest_grade = _upper(history.get("latest_known_grade"))\n    raw_counts = history.get("grade_counts") if isinstance(history.get("grade_counts"), dict) else {}\n    if independent_capable:\n        disciplinary_order = 2 if disciplinary == "Y" else 0\n        grade_order = {"C": 2, "D": 3}.get(latest_grade, 0)\n        counts = {"C": int(raw_counts.get("C") or 0), "D": int(raw_counts.get("D") or 0)}\n    else:\n        disciplinary_order = 0 if disciplinary == "N" else (2 if disciplinary == "Y" else 1)\n        counts = raw_counts\n        grade_order = {"A": 0, "B": 1, "C": 2, "D": 3, "UNKNOWN": 4}.get(latest_grade, 4)\n'''
if old not in text:
    raise SystemExit('first quality patch regulatory block not found')
path.write_text(text.replace(old, new, 1))
