export const ASSESSMENT_SCHEMA_VERSION = "family-assessment-v2.0.0";
export const UNKNOWN_FROM_FAMILY = "UNKNOWN_FROM_FAMILY";

export const DECISION_AREAS = [
  "who_needs_care", "current_location", "preferred_search_area", "urgency", "current_living_situation",
  "mobility", "daily_activities", "transfer_assistance", "medication_support", "cognitive_status",
  "nursing_needs", "rehabilitation_needs", "physical_therapy", "occupational_therapy", "speech_therapy",
  "stroke_recovery", "neurological_rehabilitation", "dietary_requirements", "language_needs",
  "religious_cultural_preferences", "social_activity_preferences", "room_preference", "budget",
  "payment_method", "distance_from_family", "family_priorities", "deal_breakers", "contact_details",
] as const;

export type DecisionArea = (typeof DECISION_AREAS)[number];
export type AssessmentAnswer = string | string[] | number;
export type AssessmentAnswers = Record<string, AssessmentAnswer>;
export type AssessmentAnswerType = "single" | "multi" | "text" | "number" | "priority";

export type AssessmentOption = {
  value: string;
  label: string;
  hebrewLabel: string;
  description?: string;
};

export type DisplayRule = {
  questionId: string;
  operator: "equals" | "includes" | "one_of";
  value: string | string[];
};

export type AssessmentQuestion = {
  id: string;
  version: typeof ASSESSMENT_SCHEMA_VERSION;
  category: string;
  decisionArea: DecisionArea;
  canonicalMappings: string[];
  englishLabel: string;
  hebrewLabel: string;
  answerType: AssessmentAnswerType;
  options?: AssessmentOption[];
  required: boolean;
  showIf?: DisplayRule;
  helpText: string;
  rankingRelevant: boolean;
  eligibilityRelevant: boolean;
  placeholder?: string;
  maxSelections?: number;
};

const option = (value: string, label: string, hebrewLabel: string, description?: string): AssessmentOption => ({ value, label, hebrewLabel, description });
const uncertainty = option(UNKNOWN_FROM_FAMILY, "Not sure", "לא בטוח/ה", "We will preserve this as unknown, not as no.");
const yesNoUnknown = [option("YES", "Yes", "כן"), option("NO", "No", "לא"), uncertainty];

const question = (input: Omit<AssessmentQuestion, "version">): AssessmentQuestion => ({ ...input, version: ASSESSMENT_SCHEMA_VERSION });

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  question({ id: "who_needs_care", category: "About your family", decisionArea: "who_needs_care", canonicalMappings: ["identity.relationship"], englishLabel: "Who are you helping find care?", hebrewLabel: "למי אתם עוזרים למצוא טיפול?", answerType: "single", required: true, helpText: "This helps us use clear, personal language throughout.", rankingRelevant: false, eligibilityRelevant: false, options: [option("Mom", "My mom", "אמא שלי"), option("Dad", "My dad", "אבא שלי"), option("Spouse", "My spouse or partner", "בן/בת הזוג שלי"), option("Myself", "Myself", "עבורי"), option("Grandparent", "My grandparent", "סבא או סבתא שלי"), option("Relative", "Another relative or friend", "קרוב/ה או חבר/ה")] }),
  question({ id: "current_location", category: "Location", decisionArea: "current_location", canonicalMappings: ["logistics.location.current"], englishLabel: "Where do they live now?", hebrewLabel: "איפה הם גרים כיום?", answerType: "text", required: true, helpText: "City or ZIP code is enough. Do not enter a full address unless it helps.", rankingRelevant: false, eligibilityRelevant: false, placeholder: "City or ZIP code" }),
  question({ id: "preferred_search_area", category: "Location", decisionArea: "preferred_search_area", canonicalMappings: ["logistics.location.preferred", "decision.location_city"], englishLabel: "Where should we search?", hebrewLabel: "באיזה אזור לחפש?", answerType: "text", required: true, helpText: "Enter a city, county, or ZIP code.", rankingRelevant: true, eligibilityRelevant: true, placeholder: "Preferred city, county, or ZIP" }),
  question({ id: "urgency", category: "Timing", decisionArea: "urgency", canonicalMappings: ["logistics.move_timeline"], englishLabel: "When might care be needed?", hebrewLabel: "מתי ייתכן שיהיה צורך בטיפול?", answerType: "single", required: true, helpText: "An estimate is enough and can be changed later.", rankingRelevant: true, eligibilityRelevant: false, options: [option("IMMEDIATE", "Now or within 7 days", "עכשיו או בתוך 7 ימים"), option("WITHIN_30_DAYS", "Within 30 days", "בתוך 30 יום"), option("ONE_TO_THREE_MONTHS", "1 to 3 months", "חודש עד שלושה חודשים"), option("EXPLORING", "Just exploring", "רק בודקים אפשרויות"), uncertainty] }),
  question({ id: "urgent_availability", category: "Timing", decisionArea: "urgency", canonicalMappings: ["recommendation_constraints.immediate_availability"], englishLabel: "Is immediate bed availability a deal-breaker?", hebrewLabel: "האם זמינות מיטה מיידית היא תנאי הכרחי?", answerType: "single", required: true, helpText: "Availability changes often and must still be verified with each facility.", rankingRelevant: true, eligibilityRelevant: false, showIf: { questionId: "urgency", operator: "one_of", value: ["IMMEDIATE", "WITHIN_30_DAYS"] }, options: yesNoUnknown }),
  question({ id: "current_living_situation", category: "Daily life", decisionArea: "current_living_situation", canonicalMappings: ["logistics.current_living_situation"], englishLabel: "What is the current living situation?", hebrewLabel: "מהו מצב המגורים הנוכחי?", answerType: "single", required: true, helpText: "This gives context without making assumptions about care needs.", rankingRelevant: false, eligibilityRelevant: false, options: [option("ALONE", "Lives alone", "גר/ה לבד"), option("WITH_FAMILY", "Lives with family", "גר/ה עם המשפחה"), option("INDEPENDENT_LIVING", "Independent living", "דיור עצמאי"), option("ASSISTED_LIVING", "Assisted living", "דיור מוגן עם סיוע"), option("HOSPITAL_REHAB", "Hospital or rehabilitation setting", "בית חולים או מסגרת שיקום"), option("OTHER", "Another situation", "מצב אחר")] }),
  question({ id: "mobility", category: "Daily support", decisionArea: "mobility", canonicalMappings: ["clinical.mobility"], englishLabel: "How do they usually get around?", hebrewLabel: "כיצד הם בדרך כלל מתניידים?", answerType: "single", required: true, helpText: "Choose the closest answer. Exact medical measurements are not needed.", rankingRelevant: true, eligibilityRelevant: true, options: [option("INDEPENDENT", "Independent", "עצמאי/ת"), option("DEVICE", "Uses a cane, walker, or wheelchair", "נעזר/ת במקל, הליכון או כיסא גלגלים"), option("SOME_HELP", "Needs some help from another person", "זקוק/ה לעזרה מסוימת מאדם אחר"), option("SIGNIFICANT_HELP", "Needs significant help", "זקוק/ה לעזרה משמעותית"), option("FULLY_DEPENDENT", "Fully dependent", "תלוי/ה לחלוטין"), uncertainty] }),
  question({ id: "daily_activities", category: "Daily support", decisionArea: "daily_activities", canonicalMappings: ["clinical.adl", "parameters.adl_support"], englishLabel: "Which daily activities need help?", hebrewLabel: "באילו פעולות יומיומיות נדרשת עזרה?", answerType: "multi", required: true, helpText: "Select all that apply.", rankingRelevant: true, eligibilityRelevant: true, options: [option("NONE", "None", "ללא"), option("BATHING", "Bathing", "רחצה"), option("DRESSING", "Dressing", "לבוש"), option("TOILETING", "Toileting", "שירותים"), option("EATING", "Eating", "אכילה"), option("MOBILITY", "Moving around", "ניידות"), uncertainty] }),
  question({ id: "transfer_assistance", category: "Daily support", decisionArea: "transfer_assistance", canonicalMappings: ["clinical.transfer_assistance", "parameters.transfer_assistance"], englishLabel: "Is help needed to move between a bed, chair, or toilet?", hebrewLabel: "האם נדרשת עזרה במעבר בין מיטה, כיסא או שירותים?", answerType: "single", required: true, helpText: "This can affect staffing and equipment requirements.", rankingRelevant: true, eligibilityRelevant: true, options: [option("INDEPENDENT", "No help needed", "אין צורך בעזרה"), option("ONE_PERSON", "One-person assistance", "עזרה של אדם אחד"), option("TWO_PERSON", "Two-person assistance", "עזרה של שני אנשים"), option("MECHANICAL_LIFT", "Mechanical lift", "מנוף מכני"), uncertainty] }),
  question({ id: "medication_support", category: "Daily support", decisionArea: "medication_support", canonicalMappings: ["clinical.medication_support", "parameters.medication_support"], englishLabel: "How much medication support is needed?", hebrewLabel: "כמה תמיכה נדרשת בניהול תרופות?", answerType: "single", required: true, helpText: "Do not guess. Not sure remains unknown.", rankingRelevant: true, eligibilityRelevant: true, options: [option("INDEPENDENT", "Manages medications independently", "מנהל/ת תרופות באופן עצמאי"), option("REMINDERS", "Needs reminders", "זקוק/ה לתזכורות"), option("ADMINISTRATION", "Needs staff to administer medications", "זקוק/ה לצוות שייתן תרופות"), option("COMPLEX", "Complex medication monitoring", "ניטור תרופות מורכב"), uncertainty] }),
  question({ id: "cognitive_status", category: "Memory and thinking", decisionArea: "cognitive_status", canonicalMappings: ["clinical.cognitive_status", "parameters.memory_care"], englishLabel: "Is memory or cognitive support relevant?", hebrewLabel: "האם תמיכה בזיכרון או בקוגניציה רלוונטית?", answerType: "single", required: true, helpText: "This is not a diagnosis. Choose what the family currently observes.", rankingRelevant: true, eligibilityRelevant: true, options: [option("NO_CONCERNS", "No current concerns", "אין חששות כרגע"), option("OCCASIONAL", "Occasionally forgetful", "שכחה מדי פעם"), option("MILD", "Mild memory issues", "קשיי זיכרון קלים"), option("SIGNIFICANT", "Significant support needed", "נדרשת תמיכה משמעותית"), uncertainty] }),
  question({ id: "nursing_needs", category: "Clinical care", decisionArea: "nursing_needs", canonicalMappings: ["clinical.nursing_needs", "parameters.nursing_24_7", "parameters.skilled_nursing_capabilities"], englishLabel: "What nursing support is needed?", hebrewLabel: "איזו תמיכה סיעודית נדרשת?", answerType: "multi", required: true, helpText: "Select only needs you know about.", rankingRelevant: true, eligibilityRelevant: true, options: [option("NONE", "No known nursing need", "אין צורך סיעודי ידוע"), option("ROUTINE", "Routine nursing oversight", "פיקוח סיעודי שגרתי"), option("24_7", "24/7 licensed nursing", "סיעוד מורשה 24/7"), option("WOUND", "Wound care", "טיפול בפצעים"), option("IV", "IV therapy", "טיפול תוך-ורידי"), option("RESPIRATORY", "Respiratory support", "תמיכה נשימתית"), uncertainty] }),
  question({ id: "rehabilitation_needed", category: "Rehabilitation", decisionArea: "rehabilitation_needs", canonicalMappings: ["clinical.rehabilitation_needed"], englishLabel: "Is rehabilitation part of the care plan?", hebrewLabel: "האם שיקום הוא חלק מתוכנית הטיפול?", answerType: "single", required: true, helpText: "We will only ask therapy details when rehabilitation is relevant.", rankingRelevant: true, eligibilityRelevant: true, options: yesNoUnknown }),
  question({ id: "rehabilitation_focus", category: "Rehabilitation", decisionArea: "rehabilitation_needs", canonicalMappings: ["clinical.rehabilitation_focus"], englishLabel: "What is the rehabilitation focus?", hebrewLabel: "מהו מוקד השיקום?", answerType: "multi", required: true, helpText: "Select all that apply.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_needed", operator: "equals", value: "YES" }, options: [option("STROKE", "Stroke recovery", "שיקום לאחר שבץ"), option("NEUROLOGICAL", "Neurological condition", "מצב נוירולוגי"), option("ORTHOPEDIC", "Orthopedic recovery", "שיקום אורתופדי"), option("CARDIAC", "Cardiac recovery", "שיקום לבבי"), option("GENERAL", "General strengthening", "חיזוק כללי"), uncertainty] }),
  question({ id: "physical_therapy", category: "Rehabilitation", decisionArea: "physical_therapy", canonicalMappings: ["clinical.therapy.pt", "parameters.pt"], englishLabel: "Is physical therapy needed?", hebrewLabel: "האם נדרש פיזיותרפיה?", answerType: "single", required: true, helpText: "Choose not sure if the discharge plan is not final.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_needed", operator: "equals", value: "YES" }, options: yesNoUnknown }),
  question({ id: "occupational_therapy", category: "Rehabilitation", decisionArea: "occupational_therapy", canonicalMappings: ["clinical.therapy.ot", "parameters.ot"], englishLabel: "Is occupational therapy needed?", hebrewLabel: "האם נדרש ריפוי בעיסוק?", answerType: "single", required: true, helpText: "This is tracked separately from physical therapy.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_needed", operator: "equals", value: "YES" }, options: yesNoUnknown }),
  question({ id: "speech_therapy", category: "Rehabilitation", decisionArea: "speech_therapy", canonicalMappings: ["clinical.therapy.speech", "parameters.speech_therapy"], englishLabel: "Is speech or swallowing therapy needed?", hebrewLabel: "האם נדרש טיפול בדיבור או בבליעה?", answerType: "single", required: true, helpText: "This remains separate from other therapy disciplines.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_needed", operator: "equals", value: "YES" }, options: yesNoUnknown }),
  question({ id: "therapy_frequency", category: "Rehabilitation", decisionArea: "rehabilitation_needs", canonicalMappings: ["clinical.therapy.frequency"], englishLabel: "Is a preferred therapy frequency known?", hebrewLabel: "האם ידועה תדירות טיפול מועדפת?", answerType: "single", required: false, helpText: "A preference is not a guarantee; the clinical team determines the treatment plan.", rankingRelevant: false, eligibilityRelevant: false, showIf: { questionId: "rehabilitation_needed", operator: "equals", value: "YES" }, options: [option("DAILY", "Daily if clinically appropriate", "יומי אם מתאים מבחינה קלינית"), option("FIVE_DAYS", "About five days per week", "כחמישה ימים בשבוע"), option("THREE_DAYS", "About three days per week", "כשלושה ימים בשבוע"), option("CLINICAL_PLAN", "Follow the clinical plan", "לפי התוכנית הקלינית"), uncertainty] }),
  question({ id: "stroke_recovery", category: "Rehabilitation", decisionArea: "stroke_recovery", canonicalMappings: ["clinical.stroke_recovery", "parameters.post_stroke_neuro_evidence"], englishLabel: "Does stroke recovery require a dedicated program?", hebrewLabel: "האם שיקום לאחר שבץ דורש תוכנית ייעודית?", answerType: "single", required: true, helpText: "This helps distinguish a structured stroke program from general rehabilitation.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_focus", operator: "includes", value: "STROKE" }, options: yesNoUnknown }),
  question({ id: "neurological_rehabilitation", category: "Rehabilitation", decisionArea: "neurological_rehabilitation", canonicalMappings: ["clinical.neurological_rehabilitation", "parameters.post_stroke_neuro_evidence"], englishLabel: "Is a neurological rehabilitation program required?", hebrewLabel: "האם נדרשת תוכנית שיקום נוירולוגי?", answerType: "single", required: true, helpText: "This is separate from a general rehabilitation claim.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "rehabilitation_focus", operator: "includes", value: "NEUROLOGICAL" }, options: yesNoUnknown }),
  question({ id: "dietary_requirements", category: "Food and diet", decisionArea: "dietary_requirements", canonicalMappings: ["culture.diet", "parameters.dietary_capabilities"], englishLabel: "Are any dietary accommodations important?", hebrewLabel: "האם יש התאמות תזונתיות חשובות?", answerType: "multi", required: true, helpText: "Select requirements, not general food preferences.", rankingRelevant: true, eligibilityRelevant: false, options: [option("NONE", "None", "ללא"), option("GLUTEN_FREE", "Gluten-free", "ללא גלוטן"), option("KOSHER", "Kosher", "כשר"), option("HALAL", "Halal", "חלאל"), option("DIABETIC", "Diabetic diet", "תזונה לסוכרת"), option("LOW_SODIUM", "Low sodium", "דל נתרן"), option("TEXTURE_MODIFIED", "Texture-modified", "מרקם מותאם"), uncertainty] }),
  question({ id: "gluten_free_details", category: "Food and diet", decisionArea: "dietary_requirements", canonicalMappings: ["culture.diet.gluten_free_safety", "parameters.gluten_free"], englishLabel: "How strict must gluten-free preparation be?", hebrewLabel: "עד כמה ההכנה ללא גלוטן חייבת להיות קפדנית?", answerType: "single", required: true, helpText: "This distinguishes preference from medically necessary cross-contamination controls.", rankingRelevant: true, eligibilityRelevant: false, showIf: { questionId: "dietary_requirements", operator: "includes", value: "GLUTEN_FREE" }, options: [option("PREFERENCE", "Preference", "העדפה"), option("MEDICALLY_REQUIRED", "Medically required", "נדרש רפואית"), option("CROSS_CONTAMINATION", "Strict cross-contamination controls required", "נדרשת מניעת זיהום צולב קפדנית"), uncertainty] }),
  question({ id: "language_needs", category: "Language and culture", decisionArea: "language_needs", canonicalMappings: ["communication.languages", "parameters.languages"], englishLabel: "Which languages matter for daily communication?", hebrewLabel: "אילו שפות חשובות לתקשורת יומיומית?", answerType: "multi", required: true, helpText: "Select all that would help the resident feel understood.", rankingRelevant: true, eligibilityRelevant: false, options: [option("ENGLISH", "English", "אנגלית"), option("SPANISH", "Spanish", "ספרדית"), option("HEBREW", "Hebrew", "עברית"), option("RUSSIAN", "Russian", "רוסית"), option("HAITIAN_CREOLE", "Haitian Creole", "קריאולית האיטית"), option("OTHER", "Another language", "שפה אחרת"), uncertainty] }),
  question({ id: "hebrew_support", category: "Language and culture", decisionArea: "language_needs", canonicalMappings: ["communication.hebrew_support", "parameters.languages"], englishLabel: "Where is Hebrew support most important?", hebrewLabel: "באילו מצבים התמיכה בעברית חשובה ביותר?", answerType: "multi", required: true, helpText: "We will not assume that a cultural program means Hebrew-speaking staff.", rankingRelevant: true, eligibilityRelevant: false, showIf: { questionId: "language_needs", operator: "includes", value: "HEBREW" }, options: [option("DAILY", "Daily conversation", "שיחה יומיומית"), option("MEDICAL", "Medical discussions", "שיחות רפואיות"), option("ACTIVITIES", "Activities and community", "פעילויות וקהילה"), option("FAMILY", "Family communication", "תקשורת עם המשפחה"), uncertainty] }),
  question({ id: "culture_importance", category: "Language and culture", decisionArea: "religious_cultural_preferences", canonicalMappings: ["culture.importance"], englishLabel: "How important is religious or cultural fit?", hebrewLabel: "עד כמה חשובה התאמה דתית או תרבותית?", answerType: "single", required: true, helpText: "This can be a preference, a high priority, or not important.", rankingRelevant: true, eligibilityRelevant: false, options: [option("NOT_IMPORTANT", "Not important", "לא חשוב"), option("SOMEWHAT", "Somewhat important", "חשוב במידה מסוימת"), option("IMPORTANT", "Important", "חשוב"), option("VERY_IMPORTANT", "Very important", "חשוב מאוד"), uncertainty] }),
  question({ id: "cultural_preferences", category: "Language and culture", decisionArea: "religious_cultural_preferences", canonicalMappings: ["culture.religion", "preferences.cultural"], englishLabel: "Which cultural or religious supports matter?", hebrewLabel: "אילו תמיכות תרבותיות או דתיות חשובות?", answerType: "multi", required: true, helpText: "Select only what would affect daily comfort or belonging.", rankingRelevant: true, eligibilityRelevant: false, showIf: { questionId: "culture_importance", operator: "one_of", value: ["SOMEWHAT", "IMPORTANT", "VERY_IMPORTANT"] }, options: [option("JEWISH", "Jewish community or programming", "קהילה או תוכן יהודי"), option("CHRISTIAN", "Christian services", "שירותים נוצריים"), option("MUSLIM", "Muslim community or prayer support", "קהילה מוסלמית או תמיכה בתפילה"), option("WORSHIP", "Access to worship", "גישה לתפילה"), option("HOLIDAYS", "Holiday observance", "ציון חגים"), option("OTHER", "Another tradition", "מסורת אחרת"), uncertainty] }),
  question({ id: "social_activity_preferences", category: "Daily life", decisionArea: "social_activity_preferences", canonicalMappings: ["preferences.activities", "parameters.activities"], englishLabel: "What would make daily life feel worthwhile?", hebrewLabel: "מה יהפוך את חיי היומיום למשמעותיים?", answerType: "multi", required: true, helpText: "Choose up to five.", rankingRelevant: true, eligibilityRelevant: false, maxSelections: 5, options: [option("SOCIAL", "Social gatherings", "מפגשים חברתיים"), option("MUSIC", "Music", "מוזיקה"), option("MOVIES", "Movies", "סרטים"), option("FITNESS", "Exercise and wellness", "פעילות גופנית ובריאות"), option("OUTDOORS", "Outdoor time", "זמן בחוץ"), option("QUIET", "Quiet time", "זמן שקט"), option("FAITH", "Faith activities", "פעילות דתית"), option("ARTS", "Arts and crafts", "אמנות ויצירה"), option("FAMILY", "Family involvement", "מעורבות משפחתית"), uncertainty] }),
  question({ id: "room_preference", category: "Living space", decisionArea: "room_preference", canonicalMappings: ["preferences.room", "parameters.private_shared_rooms"], englishLabel: "Is there a room preference?", hebrewLabel: "האם יש העדפה לסוג חדר?", answerType: "single", required: true, helpText: "Room type and availability must be verified with the facility.", rankingRelevant: true, eligibilityRelevant: false, options: [option("PRIVATE_REQUIRED", "Private room required", "נדרש חדר פרטי"), option("PRIVATE_PREFERRED", "Private room preferred", "עדיפות לחדר פרטי"), option("SHARED_OK", "Shared room is acceptable", "חדר משותף מקובל"), option("NO_PREFERENCE", "No preference", "אין העדפה"), uncertainty] }),
  question({ id: "payment_method", category: "Budget and coverage", decisionArea: "payment_method", canonicalMappings: ["financial.insurance", "parameters.payer_information"], englishLabel: "How might care be paid for?", hebrewLabel: "כיצד ייתכן שהטיפול ימומן?", answerType: "multi", required: true, helpText: "Medicare may cover eligible short-term skilled care, but it generally does not cover long-term residence.", rankingRelevant: true, eligibilityRelevant: false, options: [option("PRIVATE_PAY", "Private pay", "תשלום פרטי"), option("MEDICARE", "Medicare", "מדיקר"), option("MEDICAID", "Medicaid", "מדיקייד"), option("LTC_INSURANCE", "Long-term-care insurance", "ביטוח סיעודי"), option("OTHER_INSURANCE", "Other insurance", "ביטוח אחר"), option("NEED_GUIDANCE", "Need financial guidance", "זקוקים להכוונה כלכלית"), uncertainty] }),
  question({ id: "monthly_budget", category: "Budget and coverage", decisionArea: "budget", canonicalMappings: ["financial.budget", "parameters.published_rates"], englishLabel: "What monthly private-pay range feels manageable?", hebrewLabel: "איזה תקציב חודשי פרטי מרגיש אפשרי?", answerType: "single", required: true, helpText: "This is a planning range, not a price quote.", rankingRelevant: true, eligibilityRelevant: true, showIf: { questionId: "payment_method", operator: "includes", value: "PRIVATE_PAY" }, options: [option("UNDER_5000", "Under $5,000", "פחות מ-5,000 דולר"), option("5000_7500", "$5,000 to $7,500", "5,000 עד 7,500 דולר"), option("7500_10000", "$7,500 to $10,000", "7,500 עד 10,000 דולר"), option("10000_15000", "$10,000 to $15,000", "10,000 עד 15,000 דולר"), option("OVER_15000", "Over $15,000", "מעל 15,000 דולר"), uncertainty] }),
  question({ id: "distance_from_family", category: "Location", decisionArea: "distance_from_family", canonicalMappings: ["preferences.family_preferences", "logistics.family_distance"], englishLabel: "How close should care be to family?", hebrewLabel: "כמה קרוב הטיפול צריך להיות למשפחה?", answerType: "single", required: true, helpText: "Choose the travel time the family can realistically sustain.", rankingRelevant: true, eligibilityRelevant: false, options: [option("15_MIN", "Within 15 minutes", "עד 15 דקות"), option("30_MIN", "Within 30 minutes", "עד 30 דקות"), option("60_MIN", "Within 60 minutes", "עד 60 דקות"), option("BEST_FIT", "Best fit matters more than distance", "ההתאמה חשובה יותר מהמרחק"), uncertainty] }),
  question({ id: "family_priorities", category: "Priorities", decisionArea: "family_priorities", canonicalMappings: ["recommendation_constraints.priority_order"], englishLabel: "What matters most to your family?", hebrewLabel: "מה הכי חשוב למשפחה שלכם?", answerType: "priority", required: true, helpText: "Choose and rank up to five. A shorter list gives each priority real weight.", rankingRelevant: true, eligibilityRelevant: false, maxSelections: 5, options: [option("CLINICAL_FIT", "Clinical fit", "התאמה קלינית"), option("REHABILITATION", "Rehabilitation", "שיקום"), option("SAFETY", "Safety", "בטיחות"), option("STAFFING", "Staffing", "צוות"), option("PROXIMITY", "Proximity", "קרבה"), option("LANGUAGE", "Language", "שפה"), option("FOOD", "Food", "מזון"), option("CULTURE", "Religious or cultural fit", "התאמה דתית או תרבותית"), option("ACTIVITIES", "Activities", "פעילויות"), option("PRIVATE_ROOM", "Private room", "חדר פרטי"), option("PRICE", "Price", "מחיר"), option("AVAILABILITY", "Immediate availability", "זמינות מיידית")] }),
  question({ id: "deal_breakers", category: "Priorities", decisionArea: "deal_breakers", canonicalMappings: ["recommendation_constraints.hard_constraints"], englishLabel: "Are any of these deal-breakers?", hebrewLabel: "האם אחד מהדברים הבאים הוא תנאי הכרחי?", answerType: "multi", required: false, helpText: "Only choose factors that truly rule a facility out.", rankingRelevant: true, eligibilityRelevant: true, options: [option("NONE", "No absolute deal-breakers", "אין תנאים מוחלטים"), option("CLINICAL", "Cannot meet clinical needs", "אי יכולת לענות על צרכים קליניים"), option("DISTANCE", "Too far from family", "רחוק מדי מהמשפחה"), option("LANGUAGE", "No required language support", "אין תמיכה בשפה הנדרשת"), option("DIET", "Cannot safely meet dietary need", "אי יכולת לענות בבטחה על צורך תזונתי"), option("PRICE", "Outside the budget", "מחוץ לתקציב"), option("ROOM", "No acceptable room type", "אין סוג חדר מתאים"), option("AVAILABILITY", "No timely availability", "אין זמינות בזמן הנדרש")] }),
  question({ id: "continue_method", category: "Save and continue", decisionArea: "contact_details", canonicalMappings: ["contact.continue_method"], englishLabel: "How would you like to continue?", hebrewLabel: "כיצד תרצו להמשיך?", answerType: "single", required: true, helpText: "Your progress is already saved on this device, so no contact details are needed.", rankingRelevant: false, eligibilityRelevant: false, options: [option("CONTINUE_NOW", "Continue to results now", "להמשיך עכשיו לתוצאות"), option("SAVE_DEVICE", "Save here and review first", "לשמור כאן ולעבור על התשובות") ] }),
];

export function isQuestionVisible(question: AssessmentQuestion, answers: AssessmentAnswers): boolean {
  if (!question.showIf) return true;
  const actual = answers[question.showIf.questionId];
  if (question.showIf.operator === "equals") return actual === question.showIf.value;
  if (question.showIf.operator === "includes") return Array.isArray(actual) && actual.includes(String(question.showIf.value));
  return Array.isArray(question.showIf.value) && question.showIf.value.includes(String(actual));
}

export function getVisibleQuestions(answers: AssessmentAnswers): AssessmentQuestion[] {
  return ASSESSMENT_QUESTIONS.filter((questionItem) => isQuestionVisible(questionItem, answers));
}